# Generated by Django 6.0.3 on 2026-04-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('cooking', '🍳 Cooking'), ('cleaning', '🧹 Home Cleaning'), ('tutoring', '📚 Tutoring'), ('craft', '🎨 Craft & Handmade'), ('beauty', '💄 Beauty Services'), ('childcare', '👶 Childcare'), ('baking', '🎂 Baking'), ('digital', '💻 Digital Services')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cooking', '🍳 Cooking'), ('cleaning', '🧹 Home Cleaning'), ('tutoring', '📚 Tutoring'), ('beauty', '💄 Beauty Services'), ('childcare', '👶 Childcare'), ('craft', '🎨 Craft & Handmade'), ('baking', '🎂 Baking'), ('digital', '💻 Digital Services')], max_length=50)),
                ('description', models.TextField()),
                ('budget', models.CharField(help_text='e.g., ₹300-500/day or ₹5000/month', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('accepted', '✅ Accepted'), ('rejected', '❌ Rejected'), ('completed', '🎉 Completed')], default='pending', max_length=20)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('housewife', '👩\u200d🍳 Housewife Freelancer'), ('client', '👔 Client')], default='client', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='List your skills (for housewives)')),
                ('experience', models.TextField(blank=True, help_text='Your experience (for housewives)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
